### ISSUE TITLE
Split proxy server off into its own repo

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#12]
Now that this code is in npm, I think it makes sense to split off the proxy server or at least a copy of it given the amount of changes that will be happening to it over the next while. @redwire - what are your thoughts?

**Comment by redwire** [comment]
I think this is probably a really good idea, generally speaking, to have a library separate from an application that uses it. This is made more true by the fact that the proxy server really is configured for a specific use case.
I do have two small concerns, though, that I would like your feedback on.

1. How will we best keep track of and identify bugs in each piece of software? It'd be rather confusing to have issues on the server repo that turn out to be problems with bundler itself and vice versa.
2. Is the proxy server really a substantial enough piece of software to warrant having it's own repository for? Does maintaining a new repo impose any cost to equalitie?

**Comment by redwire** [comment]
Bill has graced us with a new repo, so please post issues specific to the server there!

https://github.com/equalitie/bundler-proxy
