### ISSUE TITLE
Use of the HTTP proxy functionality breaks remapping

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#14]
When useProxy is set to true, the Host header is no longer rewritten appropriately.

**Comment by nosmo** [comment]
I think I spoke too soon - still seeing this behaviour. Not sure why :/

**Comment by nosmo** [comment]
I believe this is related to `requests`'s use of CONNECT tunneling: https://www.npmjs.com/package/request#proxies

**Comment by redwire** [comment]
Moved to https://github.com/equalitie/bundler-proxy/issues/1
