### ISSUE TITLE
Issues Bundling pages

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#15]
There are some differences between my locally bundled version of learn.equalit.ie and the currently proxied-to instance at http://learn.distributed.deflect.ca/. They are not currently serving the same origin but they host the same content for the most part. It seems some of the issues are related to the content types of the CSS files.

**Comment by redwire** [comment]
Could you please tell me in detail how you have things configured and what I need to do to reproduce this?
I tried going to `localhost:9008?url=http://learn.distributed.deflect.ca/ and get an error saying the URL I tried to get is `undefined` and for some reason changes the URL in my address bar (redirects me?) to `localhost:9008/wiki/`.
I thought there might be an error parsing the URL there, but I can navigate to and display the bundled contents of `https://encrypted.google.com` just fine.

**Comment by kromcuich** [comment]
A better reference for this mirrored site would be the original learn.equalit.ie

D

On February 25, 2015 7:10:47 PM EST, Zack Mullaly <notifications@github.com> wrote:
>Could you please tell me in detail how you have things configured and
>what I need to do to reproduce this?
>I tried going to
>`localhost:9008?url=http://learn.distributed.deflect.ca/ and get an
>error saying the URL I tried to get is `undefined` and for some reason
>changes the URL in my address bar (redirects me?) to
>`localhost:9008/wiki/`.
>I thought there might be an error parsing the URL there, but I can
>navigate to and display the bundled contents of
>`https://encrypted.google.com` just fine.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/equalitie/bundler/issues/15#issuecomment-76091583

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nosmo** [comment]
To be clear - http://learn.distributed.deflect.ca/ is already being bundled, behind a reverse proxy and a bundle-managing service. The content being bundled should be identical to that on https://learn.equalit.ie, which bundles perfectly fine when using bundler directly - I'm curious as to why where are discrepancies.  

The redirect from / to /wiki is a little confusing when using the bundler on localhost but it works fine on the proxied version, redirecting as expected.

**Comment by redwire** [comment]
What are the discrepancies exactly?  I feel like there's a lot to try to think about here with all the reverse proxying and such going on, but I might assume some obvious discrepancies could exist due to certain resources (not) being bundled. For instance, bundler now is capable of replacing CSS values using `url()` in inline style (e.g. `<div style="background: url(...)">`) which could differ from whatever service you were using to compare.

**Comment by nosmo** [comment]
I've got a simpler example of this issue without any complicated reverse proxying. The issue seems to be that some resources aren't being seen as resources: 

Using a standard Bundler proxy to access the site directly (http://127.0.0.1:9008/?url=http://learn.equalit.ie/wiki/Main_Page) the page loads fine. 

After creating a remap in remaps.json for learn.distributed.deflect.ca to the origin (the IP address of which you've previously been provided with) the style sheets do not render properly. 

In this case it's because some of the style sheets themselves are not retrieved and so there are direct links to learn.equalit.ie in the direct access method - not a problem in and of itself, but the stylesheets themselves have not been recognised by Bundler. 
In the case of the remapped version with another domain, the links are replaced with the new domain (for example <link rel="stylesheet" href="http://learn.distributed.deflect.ca/mw/load.php?debug=false&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=erudite&amp;*" />), which in this case actually loads a bundler :)

**Comment by redwire** [comment]
@nosmo Can you give me a step-by-step to reproduce this bug?
If you could provide me with your config info, any specifics about how you're running the bundler proxy (if you are running the proxy, if not, what?), and how you invoke the server, I'd really appreciate it.
Thanks!

**Comment by nosmo** [comment]
If your remaps.json file is configured to contain: 
```
{
  "learn.distributed.deflect.ca": IP_ADDRESS
}
```
Where IP_ADDRESS is the ip address for the origin server that you were previously given. Then request: ```http://127.0.0.1:9008/?url=http://learn.equalit.ie/wiki/Main_Page```. 

With a previous version of bundler, this error would be returned: 
```
Failed to create bundle for /mw/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=erudite&version=20140801T155150Z
Error: No URL provided to bundler.
Trace
    at bundler-proxy/proxyserver.js:195:25
    at Bundler.bundle (bundler-proxy/node_modules/equalitie-bundler/src/bundler.js:63:5)
    at Server.handleRequests (bundler-proxy/proxyserver.js:191:14)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1970:22)
    at TCP.onread (net.js:527:27)
```

With the current version, the following will be returned: 
```
Got request for undefined

url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at Object.module.exports.sameHostPredicate (bundler-proxy/utils.js:56:29)
    at Server.handleRequests (bundler-proxy/proxyserver.js:103:26)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1970:22)
    at TCP.onread (net.js:527:27)
```

I believe this to be the source of the issue I mentioned, rather than any issues with proxying or other things.

**Comment by redwire** [comment]
Hey @nosmo, I've taken some time to look into the problem and identified the source of the issue.
It turns out this is a really special and rather unusual case of wikimedia committing horrible acts against HTML.  The following statement was found in `https://learn.equalit.ie/mw/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=erudite&amp;*` which is a Javascript resource referenced on http://learn.equalit.ie/wiki/Main_Page.

    document.write("\u003Cscript src=\"/mw/load.php?debug=false\u0026amp;lang=en\u0026amp;modules=jquery%2Cmediawiki\u0026amp;only=scripts\u0026amp;skin=erudite\u0026amp;version=20140801T155150Z\"\u003E\u003C/script\u003E");

So what's happening here, that is different from the other resources loaded initially, which appear to look just like the one being inserted, is that the resource is being injected into the page *after* the page is loaded and Javascript has begun executing.

Clearly we cannot reliable associate information between two separate requests, so trying to handle cases like this by keeping track of prior requests won't pan out.

**Comment by nosmo** [comment]
After our discussion earlier - should we close this as a WONTFIX?

**Comment by redwire** [comment]
Yeah.  Good point!  It is done.

**Comment by nosmo** [comment]
Resolved in bundlemanager
