### ISSUE TITLE
Move remap config to individual config file

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#6]
Currently the remap stuff lives in the proxyserver.js application - it'd be great it if could be moved to its own configuration file, in a similar simple JSON format. It'd also be nice if the location of this file could be configured via the psconfig.json file.

**Comment by redwire** [comment]
Taken care of in https://github.com/equalitie/bundler/commit/a869a1db79ba93ce1edbf18aed1f8d9350602be9
