### ISSUE TITLE
Potential encoding issue with misbehaving pages

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#8]
Accessing https://www.deflect.ca/stats/ with bundler leads to a pageful of garbled absolute nonsense. However, so does accessing the (non-bundled) page with curl. I suspect that the page is offering either a faulty encoding or no encoding whatsoever. Bundler should try its best to compensate for pages that misbehave in this manner, if possible. I don't have any suggestions for the "how" of this for now, but I'm creating this ticket for reference.

**Comment by redwire** [comment]
I get a pretty normal-looking page in Chrome.
![Screenshot](http://a.pomf.se/nfjfhh.png)

**Comment by redwire** [comment]
Using CURL, I observe that I get the [same HTML](http://pastebin.com/20Yu9uBM) as is rendered by Chrome.

**Comment by nosmo** [comment]
I think I was imagining this or something... sorry, closing!
